# Generated by Django 3.2.5 on 2021-08-02 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDetails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tododetails',
            name='title',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='tododetails',
            name='todo_data',
            field=models.CharField(max_length=225),
        ),
    ]
